# Generated by Django 6.0.3 on 2026-03-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=255)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
