# Generated by Django 6.0.3 on 2026-03-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscode',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='accesscode',
            name='used',
        ),
        migrations.RemoveField(
            model_name='shopifystore',
            name='installed_at',
        ),
        migrations.AlterField(
            model_name='shopifystore',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shopifystore',
            name='shop_domain',
            field=models.CharField(max_length=255),
        ),
    ]
