# Generated by Django 6.0.3 on 2026-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0002_remove_accesscode_product_id_remove_accesscode_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
    ]
